[build]
  command = "npm run build"
  publish = "dist" # Or your build output directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-core"

[functions]
  directory = "netlify/functions"  # Add this line to ensure the correct directory is used
